# Generated by Django 3.2.7 on 2021-09-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profession_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='documentname',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
