# Generated by Django 3.2.7 on 2021-09-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_documentname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='documentname',
        ),
    ]
